// Domain Entity - Tenant

/**
 * Régimen laboral de la empresa (Perú): define los días de vacaciones que
 * corresponden por año. 'general' = 30 días; 'micro'/'pequena' = 15 días.
 * Debe reflejar exactamente el enum `labor_regime` del backend (tabla
 * tenants), usado por el endpoint de saldo de vacaciones.
 */
export type LaborRegime = 'general' | 'micro' | 'pequena';

/** Cifrado del servidor SMTP por empresa. `null` = sin cifrado. */
export type MailEncryption = 'tls' | 'ssl';

export interface Tenant {
  id: string;
  name: string;
  ruc: string;
  business_name?: string;
  address?: string;
  phone?: string;
  logo_path?: string;
  logo_url?: string; // Public URL generated by backend
  primaryColor?: string;
  status: 'active' | 'inactive' | 'suspended';
  /** Régimen laboral: define los días de vacaciones por año (30 general / 15 micro,pequeña). */
  labor_regime?: LaborRegime;

  // --- Contadores de empleados (RP1-C / ítem 19) ---
  // initial_employee_count se fija una sola vez (idempotente) al completar
  // la primera carga masiva sobre el tenant (ver
  // UserBatch::syncInitialEmployeeCounts en backend). current_employee_count
  // es el conteo en vivo; subsequent_employee_count es la diferencia
  // (empleados agregados después de la carga inicial). Los 3 son de solo
  // lectura: el backend no expone hoy un endpoint para editar
  // initial_employee_count manualmente.
  initial_employee_count?: number;
  current_employee_count?: number;
  subsequent_employee_count?: number;

  // --- Servidor de correo (SMTP) por empresa ---
  // Campos de LECTURA que expone TenantResource. Si la empresa no configura
  // SMTP, sus correos usan el mailer por defecto de la plataforma.
  mail_host?: string;
  mail_port?: number;
  mail_username?: string;
  mail_encryption?: MailEncryption | null;
  mail_from_address?: string;
  mail_from_name?: string;
  /** El backend nunca devuelve la contraseña; solo indica si hay una guardada. */
  has_mail_password?: boolean;
  /** true cuando hay host + from_address configurados (correo propio). */
  has_custom_mailer?: boolean;

  createdAt?: Date;
  updatedAt?: Date;
  created_at?: string;
  updated_at?: string;
}

/**
 * Resultado de POST /tenants/{id}/smtp/test (botón "Probar conexión", ítem
 * 24-menor). Ver TenantService::testMailerConnection en el backend.
 */
export interface TenantSmtpTestResult {
  success: boolean;
  message: string;
}

/**
 * Campos SMTP editables (escritura). `mail_password` es WRITE-ONLY: solo se
 * envía cuando el usuario escribe una nueva contraseña. Se admite `null` para
 * poder limpiar un valor previamente guardado.
 */
export interface TenantMailInput {
  mail_host?: string | null;
  mail_port?: number | null;
  mail_username?: string | null;
  mail_password?: string;
  mail_encryption?: MailEncryption | null;
  mail_from_address?: string | null;
  mail_from_name?: string | null;
}

// Campos de solo lectura o derivados que nunca se envían en create/update.
type ReadOnlyTenantFields =
  | 'id'
  | 'createdAt'
  | 'updatedAt'
  | 'created_at'
  | 'updated_at'
  | 'logo_url'
  | 'has_mail_password'
  | 'has_custom_mailer'
  | 'initial_employee_count'
  | 'current_employee_count'
  | 'subsequent_employee_count';

export type CreateTenantData =
  Omit<Tenant, ReadOnlyTenantFields | keyof TenantMailInput> & TenantMailInput;
export type UpdateTenantData =
  Partial<Omit<Tenant, ReadOnlyTenantFields | keyof TenantMailInput>> & TenantMailInput;
